axon:
  axonserver:
    clientId: flights-query
server:
  port: 8090
spring:
  application:
    name: flights-query
  datasource:
    url: jdbc:h2:mem:flightsdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true